name: Build and Test code in notebooks

on:
  pull_request:
    branches:
      - master

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v10.1
      with:
          path: docs/source
          files: |
            \.rst$
      
    - uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.19.2'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        
    - name: Installing Dependenies
      run: |
        wget -q https://nightly.link/OpenMS/OpenMS/workflows/pyopenms-wheels/nightly/Linux-wheels.zip\?status\=completed
        mv Linux-wheels.zip\?status=completed Linux-wheels.zip
        unzip Linux-wheels.zip
        python3 -m pip install pyopenms_nightly-*-cp37-cp37*-*_x86_64.whl
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade pandocfilters jupyter
        if [ -f requirements.txt ]; then
          grep -v "pyopenms" requirements.txt > reqs_nopyoms.txt
          python3 -m pip install --upgrade -r reqs_nopyoms.txt
          rm reqs_nopyoms.txt
        fi
    
    - name: Generating notebooks
      run: |
        pushd docs/source
          ./generate_ipynb.sh
        popd

    - name: Execute all notebooks generated from modified files
      run: |
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
          jupyter nbconvert --to notebook --inplace --execute ${file%.rst}.ipynb || (echo "${file%.rst}" >> failed_nbs.txt)
        done
        if [ -f "failed_nbs.txt" ]; then
          echo "Some notebooks failed to run. Please check logs."
          cat failed_nbs.txt
          exit 1
        fi
